package:
  name: snakemakelib-workflows
  version: "0.1a.1"
source:
  git_rev: 0.1-alpha.1
  git_url: https://github.com/percyfal/snakemakelib-workflows
requirements:
  build:
    - python ==3.4.3 # As with snakemake
    - setuptools
    - snakemake >=3.4.2

  run:
    - python >=3.3
    - snakemake
    - pyyaml
    - snakemakelib_workflows

test:
  requires:
    # docs
    - sphinx >=1.3.1
    - sphinx-bootstrap-theme

    # tests
    - coverage
    - flake8
    - mock
    - pytest
    - pytest-cov ==1.8.1
  imports:
    - snakemake
    
about:
  home: https://github.com/percyfal/snakemakelib-workflows.git
  license: MIT License
  summary: 'snakemake workflows that utilize snakemakelib and snakemakelib-rules'
  
