package:
  name: snakemakelib-workflows
  version: "0.1a.2"
source:
  git_rev: "0.1-alpha.2"
  git_url: https://github.com/percyfal/snakemakelib-workflows
requirements:
  build:
    - python
    - setuptools
    - snakemake

  run:
    - python
    - snakemake
    - pyyaml
    - snakemakelib_workflows

test:
  requires:
    # docs
    - sphinx
    - sphinx-bootstrap-theme

    # tests
    - coverage
    - flake8
    - mock
    - pytest
    - pytest-cov
  imports:
    - snakemake
    
about:
  home: https://github.com/percyfal/snakemakelib-workflows.git
  license: MIT License
  summary: 'snakemake workflows that utilize snakemakelib and snakemakelib-rules'
  
